//go:generate go get -v github.com/jteeuwen/go-bindata/...
//go:generate go get -v github.com/elazarl/go-bindata-assetfs/...
//go:generate go-bindata -nomemcopy -pkg cmd -o cmd/static_content.go -ignore=.DS_Store  -ignore=README.md rai_config.yml

package main
