// Code generated by "esc -o static_content.go -pkg cmd -private ../rai_config.yml"; DO NOT EDIT.

package cmd

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	return nil, nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// _escFS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func _escFS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// _escDir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func _escDir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// _escFSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func _escFSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// _escFSMustByte is the same as _escFSByte, but panics if name is not present.
func _escFSMustByte(useLocal bool, name string) []byte {
	b, err := _escFSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// _escFSString is the string version of _escFSByte.
func _escFSString(useLocal bool, name string) (string, error) {
	b, err := _escFSByte(useLocal, name)
	return string(b), err
}

// _escFSMustString is the string version of _escFSMustByte.
func _escFSMustString(useLocal bool, name string) string {
	return string(_escFSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/rai_config.yml": {
		local:   "../rai_config.yml",
		size:    1241,
		modtime: 1509825911,
		compressed: `
H4sIAAAAAAAC/2yTSZeqPBCG9/yK7D20AgrCOS5wou3rPNDqhhMgImNCBlB//Xewh9v3fndZqeStJ29V
QUIsCYAC5sgCFMYSABWiPmbIApwKJAEQIl9EnxGsWXMdBgFizEvR3YtDCwwG9mSnqYNBa7lOlnE94vtl
tThEZnfVXrvOah0oS31yG96M+f2h7Z2tmJXupZzik9guJ5kSped6IAHAUEAR936r/5DGxXFbEpdnyD++
t8JlD/IqIWdH3JevffJI7bHBb0YYjxKTFsP70WwNb9lk5yroirExNoYcj0fji6GJ+cktj+NNFa7K3hue
m7Y9DWdUAoCiKMaFBQSTEWRcVhokzhoeLApuAUVVFa2jGp1+V//MUZx9G/cVe6GgkMe48BgKcBEyCyi9
XGIcU9S4Ryiu4hBRCzBNAsCHDHmCZha4ck6sdptpLzCHD1zAmr0EOH8anlmACD+LA5kiGEpBFqOC/906
QTIMQ88XQYq4BS5xhtgLhbFMKE5QwD/VvvKCIRpCDp9HcRZ6zYOnlveMmz8JP4+5R1EpYopyVPDnAAAg
A4oIpvyFhBcJgAT7XimQQN43jwfzUO9KTYHmi80zVIQExz80UKDKva6s6IasdAxZ0xtCIjiSlf950NB+
i8sfBjRuQsZqTH+O4XqvDLfu4rFIOuZt076aq3PVOdS4JI5mz7XO/Pa2XvcuSVR0d/vNxXFsu5w79okT
sk+5TrXoXA3v6QBIUPDrny1rTjrNVuAcxsWT5cvcZ+oT9gPvz+3omZNIb12n40uK0XmUbqrdAXdYNGKv
gVCG5gI7kb1M6/vjrYy4e9lQY+bo8akFa6cP/c36kBcQ2uUbPV18flv9LvOxOD9KqWR1pVcNb23WwvpV
ORtpsOjW+pxMk7lutBK1Gu4XDtmZSsKHq65a/3KSdHbYj3h5EOnirv5q99z8MVfU3ikQ66KOXf8c18c9
zWl/1Y7e+6/t8cqZvI+SWS8sA/h6nbHF1J2873vO0q+Vdo5vfpdNuwOJCJ8J/5/9/0j9PaKWrhnmv1u7
K06to3mv9qRyt++4dS1LZZgI0q+q04SPD9uArdR6MJD+CwAA///bFbsZ2QQAAA==
`,
	},

	"/": {
		isDir: true,
		local: "",
	},
}
