// Code generated by "esc -o static_content.go -pkg cmd -private ../rai_config.yml"; DO NOT EDIT.

package cmd

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	return nil, nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// _escFS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func _escFS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// _escDir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func _escDir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// _escFSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func _escFSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// _escFSMustByte is the same as _escFSByte, but panics if name is not present.
func _escFSMustByte(useLocal bool, name string) []byte {
	b, err := _escFSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// _escFSString is the string version of _escFSByte.
func _escFSString(useLocal bool, name string) (string, error) {
	b, err := _escFSByte(useLocal, name)
	return string(b), err
}

// _escFSMustString is the string version of _escFSMustByte.
func _escFSMustString(useLocal bool, name string) string {
	return string(_escFSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/rai_config.yml": {
		local:   "../rai_config.yml",
		size:    1368,
		modtime: 1536440962,
		compressed: `
H4sIAAAAAAAC/2xUSZOiTBC98yvqbqACCkKEB9xoe9y3Vi9EASWyVlELqL/+C7S7p2e+ORFJRuV7+V5m
QkIsCYAcZsgCFEYSACWiHmbIAheYMiQBECBPhF8hrFj9APo+YsxN0N2NAgv0+/Z4q6n9fmOxihdRNeS7
RTnfh2Zn2VodnOXKVxb6+Da4GbP7Q9s5GzEtDpdigk9isxinSpicq74EAEM+Rdz9Xf1HaZwfNwU58BR5
x49GsOhCXsbk7Ij74q1HHok9MvjNCKJhbNJ8cD+ajcEtHW8PCrpibIyMAcej4ehiaGJ2OhTH0boMlkX3
Hc9M254EUyoBQFEY4dwCgskIMi4rNSXOaj5Y5NwCiqoqWls12r2O/pmjOP2W7it2A0Ehj3DuMuTjPGAW
ULqZxDimqFaPUFxGAaIWYJoEgAcZcgVNLXDlnFitFtOaMIMPnMOKNX2cPQVPLUCEl0a+TBEMJD+NUM7/
Nk+QFMPA9YSfIG6BS5Qi1qQwkgnFMfL5Z7WvvGCIBpDD568oDdz6wbOW+4zrnoSXRdylqBARRRnK+XMA
AJABRQRT3iTBRQIgxp5bCCSQ+83HhVmgd2ryOUzvPPI/Ld3bstI2u6phtHuyItUEagnqsigPCI5+YCBf
lbsdWdENWWkbsqbXHRDBkaz8T6O6m29w+SVQrTZkrML055iudspgc5g/5nHbvK1bV3N5Ltv7ChfE0eyZ
1p7d3ler7iUO8852t744jm0XM8c+cUJ2CdepFp7LwT3pS1Dw65+O1n/a9dbgDEb5k8qX9s/UJ9cXuz+X
p2uOQ71xnYwuCUbnYbIut3vcZuGQvflCGZhz7IT2Iqnuj/ci5IfLmhpTR49ODVg5PeitV/ssh9Au3unp
4vHb8jfMa69+QKlkeaVXDW9s1sD6VTkbiT/vVPqMTOKZbjRitRzs5g7ZmkrMB8uOWv1y4mS63w15sRfJ
/K7+anUP2WOmqN2TL1Z5FR28c1QddzSjvWUr/Oi9tUZLZ/wxjKfdoPDh23XK5pPD+GPXdRZepbQyfPM6
bNLpS0R4THj/tP+V+nuCLV0zzH87u81PjaN5L3ekPGw+cONaFMogFqRXlqcxH+03PluqVb8vpTgMEa1x
UlSi1HqdOQmAK8bJN35I4T3FofT5fZ6+IKCIMQtonaZimk2lZzZ7as0G09eJaCvSfwEAAP//bvfbAlgF
AAA=
`,
	},

	"/": {
		isDir: true,
		local: "",
	},
}
